version: "3"

services:
  vscode_atcoder_rust:
    container_name: vscode_atcoder_rust
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "7878:7878"
